version: 2

workflows:
    version: 2
    test:
        jobs:
            - test-3.6

jobs:
    test-3.6:
        docker:
            - image: circleci/python:3.6-browsers
        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

            - run:
                name: Create virtualenv
                command: |
                    python3 -m venv venv

            - run:
                name: Install requirements
                command: |
                    . venv/bin/activate
                    pip install -r requirements.txt --quiet

            - save_cache:
                key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
                paths:
                    - "venv"

            - run:
                name: Run lint
                command: |
                    . venv/bin/activate
                    flake8 *.py
                    pylint *.py --rcfile .pylintrc
                when: always
